## Untuk membaca data

In [1]:
import pandas as pd

# Karena notebook ini ada di folder 'notebooks', kita gunakan '../' untuk mundur satu langkah
# lalu masuk ke folder 'data/processed'
path_master = '../data/processed/master_renaksi_bps_terintegrasi.csv'
path_target = '../data/processed/target_output_terintegrasi.csv'

df_master = pd.read_csv(path_master)
df_target = pd.read_csv(path_target)

print("Data berhasil dimuat!")

Data berhasil dimuat!

## Memahami struktur Tabel - Master

In [5]:
# 1. Melihat 5 baris pertama untuk mendapat gambaran bentuk data
display(df_master.head())

,no,indikator_utama,hasil_2025,target_2026,catatan_lhe,rencana_aksi_desc,satuan,indikator_output,tw1,tw2,tw3,tw4,target_total,anggaran,keterangan,pic_koordinator,pic_pelaksana,kategori_tematik
0,1,Nilai SAKIP,"78,89","79,03",Badan Pusat Statistik perlu memperkuat keterka...,1. Diskusi dengan MenPANRB untuk penjelasan le...,Kegiatan,Laporan Rencana Tindak Lanjut rekomendasi AKIP...,0,1,1,1,1,NaN,NaN,Biro Perencanaan dan Kerjasama,Biro Perencanaan dan Kerjasama,RB General
1,1,Nilai SAKIP,"78,89","79,03",Badan Pusat Statistik perlu memperkuat keterka...,2. Benchmarking ke K/L untuk mendapatkan saran...,Kegiatan,Laporan benchmarking ke K/L,0,1,1,1,1,NaN,NaN,Biro Perencanaan dan Kerjasama,Biro Perencanaan dan Kerjasama,RB General
2,1,Nilai SAKIP,"78,89","79,03",Badan Pusat Statistik perlu memperkuat keterka...,3. Penyusunan reviu Indikator Kinerja Utama 20...,Persen,Draf Reviu Perka IKU 2025-2029,25,50,75,100,100,NaN,NaN,Biro Perencanaan dan Kerjasama,Biro Perencanaan dan Kerjasama,RB General
3,1,Nilai SAKIP,"78,89","79,03",Badan Pusat Statistik perlu memperkuat keterka...,4. Perbaikan CSF sehingga keterkaitan logis me...,Dokumen,Dokumen Perencanaan Kinerja yang memuat perbai...,0,0,1,1,1,NaN,NaN,Biro Perencanaan dan Kerjasama,Biro Perencanaan dan Kerjasama,RB General
4,1,Nilai SAKIP,"78,89","79,03",Badan Pusat Statistik perlu memperkuat keterka...,5. Perbaikan dokumen pohon kinerja yang konsis...,Dokumen,Dokumen Perencanaan Kinerja yang memuat perbai...,0,0,1,1,1,NaN,NaN,Biro Perencanaan dan Kerjasama,Biro Perencanaan dan Kerjasama,RB General

In [8]:
# 2. Melihat informasi tipe data dan apakah masih ada data yang kosong (Null)
print("\n--- INFORMASI TABEL MASTER ---")
df_master.info()

--- INFORMASI TABEL MASTER ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   no                 162 non-null    object
 1   indikator_utama    156 non-null    object
 2   hasil_2025         162 non-null    object
 3   target_2026        163 non-null    object
 4   catatan_lhe        157 non-null    object
 5   rencana_aksi_desc  163 non-null    object
 6   satuan             142 non-null    object
 7   indikator_output   145 non-null    object
 8   tw1                133 non-null    object
 9   tw2                132 non-null    object
 10  tw3                137 non-null    object
 11  tw4                144 non-null    object
 12  target_total       142 non-null    object
 13  anggaran           58 non-null     object
 14  keterangan         43 non-null     object
 15  pic_koordinator    130 non-null    object
 16  pic_pelaksana      101 non-null    object
 17  kategori_tematik   163 non-null    object
dtypes: object(18)
memory usage: 23.1+ KB

In [17]:
# 3. Melihat siapa saja PIC Pelaksana yang terlibat
print("\n--------------------- DAFTAR PIC PELAKSANA --------------------\n")
print(df_master['pic_pelaksana'].unique())

--------------------- DAFTAR PIC PELAKSANA --------------------

['Biro Perencanaan dan Kerjasama' '1.Biro Perencanaan dan Kerjasama'
 '1.Biro Perencanaan dan Kerjasama\n2. Dir SIS'
 'Biro Perencanaan dan Kerja Sama' 'Tim Penyusunan Rencana'
 'Bagian Manajemen Risiko dan Dukungan Strategis Pimpinan'
 'Tim Monitoring dan Evaluasi Program - Lidya Indah Aribi'
 'Tim Konsolidasi - Dwi Wulan' nan 'Surya Ramadhana'
 'Arcci Surya Adhitya Sriyantoro' 'Atang Suhendi' 'Arif Rosyanto'
 'Tri Purwanto' 'Ranny Puspitasari' 'Wuri Hariyati'
 'Biro Keuangan dan BMN, Biro Perencanaan dan Kerjasama, Biro Hukum dan Organisasi, dan Inspektorat Utama'
 'Biro Keuangan dan BMN' 'Bagian Pengelolaan Barang Milik Negara'
 'Biro SDM'
 'Direktorat Diseminasi, Pemberdayaan dan Evaluasi Penyelenggaraan Statistik'
 'Direktorat Diseminasi, Pemberdayaan, dan Evaluasi Penyelenggaraan Statistik (Walidata)'
 'Subdit Evaluasi Penyelenggaraan Statistik'
 'Tim Pengelolaan Perpustakaan dan Produk Statistik' 'Tim Kerja sama'
 'Tim Data Sains' 'Yulia Virantina'
 'Pengawasan Tindak Lanjut Hasil Pemeriksaan Eksternal dan Konsultansi atas Pengelolaan Keuangan Negara'
 'Tim 07' '1' '0' '\xa0' '2' '-' '0,-' 'Ida Fariana\n081217612193']

## Memahami Tabel - Target ( hasil unipivot )

In [18]:
# 1. Melihat 5 baris pertama data target
display(df_target.head())

,no,rencana_aksi_desc,satuan,indikator_output,kategori_tematik,periode_tw,target_penyelesaian
0,1,1. Diskusi dengan MenPANRB untuk penjelasan le...,Kegiatan,Laporan Rencana Tindak Lanjut rekomendasi AKIP...,RB General,tw1,0
1,1,2. Benchmarking ke K/L untuk mendapatkan saran...,Kegiatan,Laporan benchmarking ke K/L,RB General,tw1,0
2,1,3. Penyusunan reviu Indikator Kinerja Utama 20...,Persen,Draf Reviu Perka IKU 2025-2029,RB General,tw1,25
3,1,4. Perbaikan CSF sehingga keterkaitan logis me...,Dokumen,Dokumen Perencanaan Kinerja yang memuat perbai...,RB General,tw1,0
4,1,5. Perbaikan dokumen pohon kinerja yang konsis...,Dokumen,Dokumen Perencanaan Kinerja yang memuat perbai...,RB General,tw1,0

In [19]:
# 2. Mari kita buktikan kebingungan Anda tentang kolom target yang berisi teks
print("\n--- SAMPEL ISI KOLOM TARGET PENYELESAIAN ---")
# Menampilkan 20 nilai unik pertama dari kolom target_penyelesaian
print(df_target['target_penyelesaian'].unique()[:20])

--- SAMPEL ISI KOLOM TARGET PENYELESAIAN ---
['0' '25' '1' '100' '50' '2' '75' '3' '4' nan '20' '60' '80' '0.25' '0.5'
 '0.75' '0.4' '0.6' '0.8' '6.57']

## Filter Sederhana (seperti sistem di dashboard)

In [20]:
# Mari kita simulasikan bagaimana dashboard memfilter data
# Contoh: Kita hanya ingin melihat Rencana Aksi untuk tematik "Kemiskinan"

df_kemiskinan = df_master[df_master['kategori_tematik'] == 'RB Tematik 1. Kemiskinan']
print(f"Total kegiatan untuk Kemiskinan: {len(df_kemiskinan)} kegiatan")

# Tampilkan data khusus kemiskinan
display(df_kemiskinan.head())

Total kegiatan untuk Kemiskinan: 0 kegiatan

Empty DataFrame
Columns: [no, indikator_utama, hasil_2025, target_2026, catatan_lhe, rencana_aksi_desc, satuan, indikator_output, tw1, tw2, tw3, tw4, target_total, anggaran, keterangan, pic_koordinator, pic_pelaksana, kategori_tematik]
Index: []